Fixed some bugs in timestop
HYU-SDP-IamJAVAman/Invaders-SDP-Midterm pull request #32
Opened 2024-10-17 16:28 UTC by D0hunLee

Fixed a bug where the bomb and linebomb were not triggered during 'timestop' activation.

Now, 'timestop' can stop the enemy's movements and attacks at the same time.

Added a boolean parameter to the update and shoot methods to control the movement and attack of enemies in the EnemyShipFormation.

2024-10-18 03:18 UTC, javadocq commented
In your code, the item has a probability of 100. This needs to be corrected.

2024-10-18 03:25 UTC, D0hunLee commented
> In your code, the item has a probability of 100. This needs to be corrected.

I forgot to restore the probability values after changing them for testing purposes. I will correct them and upload again.

2024-11-07 10:52 UTC, dev-moonsc requested changes
LGTM but some minor suggestions.

2024-11-07 10:52 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
> -
This blank line must be present as it serves to separate instance field declarations from default field declarations.

2024-11-07 10:52 UTC, dev-moonsc commented on src/engine/ItemManager.java
> +
I think this blank line is unnecessary.

2024-11-07 10:52 UTC, dev-moonsc commented on src/engine/ItemManager.java
> +
I think it would be better to have only one blank line here.

2024-11-07 10:52 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
> +
This blank line looks unnecessary.

2024-11-07 10:52 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
>  			positionY += movementY;
How about this?
```suggestion

			// Stop the movements of enemy ships when 'isTimeStopActive' is true.
			if (!isTimestopActive) {
				positionX += movementX;
				positionY += movementY;
			}
```

2024-11-07 10:52 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
> +		}
As suggested above, why not wrap the code that shoot the bullet itself in an `if (!isTimeStopActive)` statement?

2024-11-07 11:46 UTC, D0hunLee commented
> LGTM but a minor suggestion.

I reflected reviews. plz check.

2024-11-07 11:47 UTC, dev-moonsc approved these changes
LGTM :)

2024-11-07 11:51 UTC, merged